project:
  type: website
  output-dir: docs

website:
  title: "Lexi Knight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"
        href: Alexandra_Knight_CV.pdf

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual




