---
title: "Welcome to my Website"
---

Introduction:

My name is Lexi and I grew up on the West Coast of Canada specifically Victoria BC. I chose to attend post-secondary education at the University of Toronto partly because my mother attended the University however the main contributor however was representing the University playing Field Hockey. After completing my bachelors of Science, I will be taking ten months off to work explore New Zealand's North Island before doing a masters at Univerity of Otago on the South Island. I am still deciding on a masters program, however at the moment I am most interested in the Physiology Program to become a registered physio to follow my passion of sports and helping people.

See "**About**" page for further information regarding my education, skills, projects, experience, interests and hobbies.

See "**CV**" for my personal and up to date resume.

Contact information:

Email: knight.alexandra8\@gmail.com

LinkedIn: Lexi Knight

GitHub: LexiKnight

Facebook: Lexi Knight

Instagram: FH_lex
